### ISSUE TITLE
Question about "SementicEvaluator"

### ISSUE THREAD

**Issue by hyo03** [Daniellli/PAD#2]
Hi, thanks for your nice work!
I have a question about how to import SementicEvaluator (in line56 of anomaly_semantic_kitti/trainer.py).
I would really appreciate it if you could let me know :) Thanks in advance!

**Comment by Daniellli** [comment]
Hi, sorry for the late response.
You can use [this repo](https://github.com/Jun-CEN/semantic_kitti_api) for the evaluation, which was released by the author of REAL. In our work, we just reconstructed the evaluation code for efficiency. The reconstructed code is available [here](https://github.com/Daniellli/semantic_kitti_api.git).

**Comment by hyo03** [comment]
Thank you for your help :)
I have one more question: Which dataset should I download if I want to exactly replicate the structure of the ShapeNet dataset? I currently downloaded ShapeNetSem and ShapeNetCore.v1 from Hugging Face, but both of them have different structures.

**Comment by Daniellli** [comment]
Hi,  thank you for your interest. 
We use ShapeNetCore in our experiments.

Best regards,
Daniel
